# Generated by Django 5.0.1 on 2024-01-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_price', models.CharField(max_length=128)),
                ('inscription_number_min', models.CharField(max_length=128)),
                ('inscription_number_max', models.CharField(max_length=128)),
                ('owners', models.CharField(max_length=32)),
                ('pending_transactions', models.IntegerField()),
                ('supply', models.IntegerField()),
                ('total_listed', models.IntegerField()),
                ('total_volume', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CollectionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_symbol', models.CharField(max_length=32)),
            ],
        ),
    ]
